package org.lange.tennis.levelr.service.calculator.impl.v1

/**
 * Shared test scenarios for NTRP and UTR rating calculations.
 * Used by both PerformanceBasedRankingCalculatorImplTest and NTRPvsUTRComparison.
 */
data class RatingScenario(
    val id: String,
    val description: String,
    val ntrpP1: String,
    val ntrpP2: String,
    val utrP1: String,
    val utrP2: String,
    val p1Games: Int,
    val p2Games: Int,
    val winner: String,
    val expectedNtrpP1Delta: String,
    val expectedNtrpP2Delta: String,
    val expectedUtrP1Delta: String,
    val expectedUtrP2Delta: String,
    val smoothingEnabled: Boolean = false,
    val smoothingFactor: Double = 0.5,
)

object TestScenarios {
    /**
     * All test scenarios covering various rating levels and match outcomes.
     * Scenarios are sorted by rating level (low to high).
     *
     * NTRP uses 0.5 competitive threshold (8.3% of 6.0 range).
     * UTR uses 1.25 competitive threshold (8.3% of 15.0 range).
     * K-factor scaling: K_UTR = 2.5 × K_NTRP, so UTR deltas = 2.5 × NTRP deltas.
     */
    val allScenarios =
        listOf(
            // NTRP 2.5 level (UTR 5.0 level)
            RatingScenario(
                id = "S1",
                description = "Low: Equal players, dominant (6-0)",
                ntrpP1 = "2.5",
                ntrpP2 = "2.5",
                utrP1 = "5.0",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.160000",
                expectedNtrpP2Delta = "-0.160000",
                expectedUtrP1Delta = "0.400000",
                expectedUtrP2Delta = "-0.400000",
            ),
            RatingScenario(
                id = "S2",
                description = "Low: Equal players, close (6-4)",
                ntrpP1 = "2.5",
                ntrpP2 = "2.5",
                utrP1 = "5.0",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.032000",
                expectedNtrpP2Delta = "-0.032000",
                expectedUtrP1Delta = "0.080000",
                expectedUtrP2Delta = "-0.080000",
            ),
            RatingScenario(
                id = "S3",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "2.6",
                ntrpP2 = "2.5",
                utrP1 = "5.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            RatingScenario(
                id = "S4",
                description = "Low: 0.5 gap, expected win (6-0)",
                ntrpP1 = "3.0",
                ntrpP2 = "2.5",
                utrP1 = "6.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S5",
                description = "Low: 0.5 gap, expected win (6-4)",
                ntrpP1 = "3.0",
                ntrpP2 = "2.5",
                utrP1 = "6.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S6",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "3.1",
                ntrpP2 = "3.0",
                utrP1 = "6.5",
                utrP2 = "6.25",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            RatingScenario(
                id = "S7",
                description = "Low: 1.0 gap, expected win (6-0)",
                ntrpP1 = "3.5",
                ntrpP2 = "2.5",
                utrP1 = "7.5",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S8",
                description = "Low: 1.0 gap, upset (6-0)",
                ntrpP1 = "2.5",
                ntrpP2 = "3.5",
                utrP1 = "5.0",
                utrP2 = "7.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.642572",
                expectedNtrpP2Delta = "-0.642572",
                expectedUtrP1Delta = "1.606429",
                expectedUtrP2Delta = "-1.606429",
            ),
            RatingScenario(
                id = "S9",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "3.6",
                ntrpP2 = "3.5",
                utrP1 = "7.75",
                utrP2 = "7.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            RatingScenario(
                id = "S10",
                description = "Low: 1.5 gap, expected win (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "2.5",
                utrP1 = "8.75",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S11",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "4.1",
                ntrpP2 = "4.0",
                utrP1 = "9.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            // NTRP 4.0-4.5 level (UTR 8.75-10.0 level)
            RatingScenario(
                id = "S12",
                description = "Mid: 2.0 gap, big upset (6-0)",
                ntrpP1 = "2.5",
                ntrpP2 = "4.5",
                utrP1 = "5.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "1.285139",
                expectedNtrpP2Delta = "-1.285139",
                expectedUtrP1Delta = "3.212848",
                expectedUtrP2Delta = "-3.212848",
            ),
            RatingScenario(
                id = "S13",
                description = "Mid: Expected win, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S14",
                description = "Mid: Expected win, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S15",
                description = "Mid: Upset, dominant (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "8.75",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.321284",
                expectedNtrpP2Delta = "-0.321284",
                expectedUtrP1Delta = "0.803210",
                expectedUtrP2Delta = "-0.803210",
            ),
            RatingScenario(
                id = "S16",
                description = "Mid: Upset, close (6-4)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "8.75",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.064257",
                expectedNtrpP2Delta = "-0.064257",
                expectedUtrP1Delta = "0.160642",
                expectedUtrP2Delta = "-0.160642",
            ),
            RatingScenario(
                id = "S17",
                description = "Mid: Competitive, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.3",
                utrP1 = "10.0",
                utrP2 = "9.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.095744",
                expectedNtrpP2Delta = "-0.095744",
                expectedUtrP1Delta = "0.239359",
                expectedUtrP2Delta = "-0.239359",
            ),
            RatingScenario(
                id = "S18",
                description = "Mid: Competitive, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.3",
                utrP1 = "10.0",
                utrP2 = "9.5",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.019149",
                expectedNtrpP2Delta = "-0.019149",
                expectedUtrP1Delta = "0.047872",
                expectedUtrP2Delta = "-0.047872",
            ),
            RatingScenario(
                id = "S19",
                description = "Mid: Equal players, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.5",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.160000",
                expectedNtrpP2Delta = "-0.160000",
                expectedUtrP1Delta = "0.400000",
                expectedUtrP2Delta = "-0.400000",
            ),
            RatingScenario(
                id = "S20",
                description = "Mid: Equal players, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.5",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.032000",
                expectedNtrpP2Delta = "-0.032000",
                expectedUtrP1Delta = "0.080000",
                expectedUtrP2Delta = "-0.080000",
            ),
            RatingScenario(
                id = "S21",
                description = "Mid: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "4.6",
                ntrpP2 = "4.5",
                utrP1 = "10.25",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            // NTRP 4.0-5.0 level (UTR 10.0-12.5 level) - Large gaps
            RatingScenario(
                id = "S22",
                description = "High: Large gap, expected win (6-0)",
                ntrpP1 = "5.0",
                ntrpP2 = "4.0",
                utrP1 = "12.5",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S23",
                description = "High: Large gap, big upset (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "5.0",
                utrP1 = "10.0",
                utrP2 = "12.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.642572",
                expectedNtrpP2Delta = "-0.642572",
                expectedUtrP1Delta = "1.606429",
                expectedUtrP2Delta = "-1.606429",
            ),
            RatingScenario(
                id = "S24",
                description = "High: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "5.1",
                ntrpP2 = "5.0",
                utrP1 = "12.75",
                utrP2 = "12.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            // Smoothing scenarios - Equal players with different smoothing factors
            RatingScenario(
                id = "SM1",
                description = "Smoothing 0.3: Equal, dominant (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.048000",
                expectedNtrpP2Delta = "-0.048000",
                expectedUtrP1Delta = "0.120000",
                expectedUtrP2Delta = "-0.120000",
                smoothingEnabled = true,
                smoothingFactor = 0.3,
            ),
            RatingScenario(
                id = "SM2",
                description = "Smoothing 0.5: Equal, dominant (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.080000",
                expectedNtrpP2Delta = "-0.080000",
                expectedUtrP1Delta = "0.200000",
                expectedUtrP2Delta = "-0.200000",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM3",
                description = "Smoothing 0.7: Equal, dominant (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.112000",
                expectedNtrpP2Delta = "-0.112000",
                expectedUtrP1Delta = "0.280000",
                expectedUtrP2Delta = "-0.280000",
                smoothingEnabled = true,
                smoothingFactor = 0.7,
            ),
            RatingScenario(
                id = "SM4",
                description = "Smoothing 0.3: Equal, close (6-4)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.009600",
                expectedNtrpP2Delta = "-0.009600",
                expectedUtrP1Delta = "0.024000",
                expectedUtrP2Delta = "-0.024000",
                smoothingEnabled = true,
                smoothingFactor = 0.3,
            ),
            RatingScenario(
                id = "SM5",
                description = "Smoothing 0.5: Equal, close (6-4)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.016000",
                expectedNtrpP2Delta = "-0.016000",
                expectedUtrP1Delta = "0.040000",
                expectedUtrP2Delta = "-0.040000",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM6",
                description = "Smoothing 0.5: Upset (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "10.0",
                utrP2 = "11.25",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.160642",
                expectedNtrpP2Delta = "-0.160642",
                expectedUtrP1Delta = "0.401605",
                expectedUtrP2Delta = "-0.401605",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            // Non-competitive smoothing scenarios: Expected wins (favorite beats underdog)
            RatingScenario(
                id = "SM7",
                description = "Smoothing 0.5: Expected win at threshold",
                ntrpP1 = "4.5",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM8",
                description = "Smoothing 0.5: Competitive gap, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.3",
                utrP1 = "10.0",
                utrP2 = "9.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.047872",
                expectedNtrpP2Delta = "-0.047872",
                expectedUtrP1Delta = "0.119680",
                expectedUtrP2Delta = "-0.119680",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM9",
                description = "Smoothing 0.3: Competitive gap, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.3",
                utrP1 = "10.0",
                utrP2 = "9.5",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.005745",
                expectedNtrpP2Delta = "-0.005745",
                expectedUtrP1Delta = "0.014362",
                expectedUtrP2Delta = "-0.014362",
                smoothingEnabled = true,
                smoothingFactor = 0.3,
            ),
            // Non-competitive smoothing scenarios: Upsets with different factors
            RatingScenario(
                id = "SM10",
                description = "Smoothing 0.3: Small upset (6-4)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "8.75",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.019277",
                expectedNtrpP2Delta = "-0.019277",
                expectedUtrP1Delta = "0.048193",
                expectedUtrP2Delta = "-0.048193",
                smoothingEnabled = true,
                smoothingFactor = 0.3,
            ),
            RatingScenario(
                id = "SM11",
                description = "Smoothing 0.7: Medium upset (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "8.75",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.224899",
                expectedNtrpP2Delta = "-0.224899",
                expectedUtrP1Delta = "0.562247",
                expectedUtrP2Delta = "-0.562247",
                smoothingEnabled = true,
                smoothingFactor = 0.7,
            ),
            RatingScenario(
                id = "SM12",
                description = "Smoothing 0.5: Large upset (1.0 gap)",
                ntrpP1 = "2.5",
                ntrpP2 = "3.5",
                utrP1 = "5.0",
                utrP2 = "7.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.321286",
                expectedNtrpP2Delta = "-0.321286",
                expectedUtrP1Delta = "0.803214",
                expectedUtrP2Delta = "-0.803214",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM13",
                description = "Smoothing 0.3: Huge upset (2.0 gap)",
                ntrpP1 = "2.5",
                ntrpP2 = "4.5",
                utrP1 = "5.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.385542",
                expectedNtrpP2Delta = "-0.385542",
                expectedUtrP1Delta = "0.963854",
                expectedUtrP2Delta = "-0.963854",
                smoothingEnabled = true,
                smoothingFactor = 0.3,
            ),
            // Non-competitive smoothing scenarios: Below threshold gaps
            RatingScenario(
                id = "SM14",
                description = "Smoothing 0.5: Small gap (0.1), dominant",
                ntrpP1 = "4.1",
                ntrpP2 = "4.0",
                utrP1 = "9.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.063935",
                expectedNtrpP2Delta = "-0.063935",
                expectedUtrP1Delta = "0.159839",
                expectedUtrP2Delta = "-0.159839",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM15",
                description = "Smoothing 0.7: Small gap (0.1), close",
                ntrpP1 = "4.6",
                ntrpP2 = "4.5",
                utrP1 = "10.25",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "T1",
                expectedNtrpP1Delta = "0.017902",
                expectedNtrpP2Delta = "-0.017902",
                expectedUtrP1Delta = "0.044755",
                expectedUtrP2Delta = "-0.044755",
                smoothingEnabled = true,
                smoothingFactor = 0.7,
            ),
            // Non-competitive smoothing scenarios: Boundary conditions
            RatingScenario(
                id = "SM16",
                description = "Smoothing 0.5: High rating upset",
                ntrpP1 = "4.0",
                ntrpP2 = "5.0",
                utrP1 = "10.0",
                utrP2 = "12.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.321286",
                expectedNtrpP2Delta = "-0.321286",
                expectedUtrP1Delta = "0.803214",
                expectedUtrP2Delta = "-0.803214",
                smoothingEnabled = true,
                smoothingFactor = 0.5,
            ),
            RatingScenario(
                id = "SM17",
                description = "Smoothing 0.3: Low rating levels",
                ntrpP1 = "2.6",
                ntrpP2 = "2.5",
                utrP1 = "5.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.038361",
                expectedNtrpP2Delta = "-0.038361",
                expectedUtrP1Delta = "0.095903",
                expectedUtrP2Delta = "-0.095903",
                smoothingEnabled = true,
                smoothingFactor = 0.3,
            ),
            RatingScenario(
                id = "SM18",
                description = "Smoothing 0.7: High rating levels",
                ntrpP1 = "5.1",
                ntrpP2 = "5.0",
                utrP1 = "12.75",
                utrP2 = "12.5",
                p1Games = 6,
                p2Games = 0,
                winner = "T1",
                expectedNtrpP1Delta = "0.089510",
                expectedNtrpP2Delta = "-0.089510",
                expectedUtrP1Delta = "0.223774",
                expectedUtrP2Delta = "-0.223774",
                smoothingEnabled = true,
                smoothingFactor = 0.7,
            ),
        )
}
