package org.lange.tennis.levelr.service.calculator.impl.v1

/**
 * Shared test scenarios for NTRP and UTR rating calculations.
 * Used by both PerformanceBasedRankingCalculatorImplTest and NTRPvsUTRComparison.
 */
data class RatingScenario(
    val id: String,
    val description: String,
    val ntrpP1: String,
    val ntrpP2: String,
    val utrP1: String,
    val utrP2: String,
    val p1Games: Int,
    val p2Games: Int,
    val winner: String,
    val expectedNtrpP1Delta: String,
    val expectedNtrpP2Delta: String,
    val expectedUtrP1Delta: String,
    val expectedUtrP2Delta: String,
)

object TestScenarios {
    /**
     * All test scenarios covering various rating levels and match outcomes.
     * Scenarios are sorted by rating level (low to high).
     *
     * NTRP uses 0.5 competitive threshold (8.3% of 6.0 range).
     * UTR uses 1.25 competitive threshold (8.3% of 15.0 range).
     * K-factor scaling: K_UTR = 2.5 × K_NTRP, so UTR deltas = 2.5 × NTRP deltas.
     */
    val allScenarios =
        listOf(
            // NTRP 2.5 level (UTR 5.0 level)
            RatingScenario(
                id = "S1",
                description = "Low: Equal players, dominant (6-0)",
                ntrpP1 = "2.5",
                ntrpP2 = "2.5",
                utrP1 = "5.0",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.160000",
                expectedNtrpP2Delta = "-0.160000",
                expectedUtrP1Delta = "0.400000",
                expectedUtrP2Delta = "-0.400000",
            ),
            RatingScenario(
                id = "S2",
                description = "Low: Equal players, close (6-4)",
                ntrpP1 = "2.5",
                ntrpP2 = "2.5",
                utrP1 = "5.0",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 4,
                winner = "P1",
                expectedNtrpP1Delta = "0.032000",
                expectedNtrpP2Delta = "-0.032000",
                expectedUtrP1Delta = "0.080000",
                expectedUtrP2Delta = "-0.080000",
            ),
            RatingScenario(
                id = "S3",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "2.6",
                ntrpP2 = "2.5",
                utrP1 = "5.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            RatingScenario(
                id = "S4",
                description = "Low: 0.5 gap, expected win (6-0)",
                ntrpP1 = "3.0",
                ntrpP2 = "2.5",
                utrP1 = "6.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S5",
                description = "Low: 0.5 gap, expected win (6-4)",
                ntrpP1 = "3.0",
                ntrpP2 = "2.5",
                utrP1 = "6.25",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 4,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S6",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "3.1",
                ntrpP2 = "3.0",
                utrP1 = "6.5",
                utrP2 = "6.25",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            RatingScenario(
                id = "S7",
                description = "Low: 1.0 gap, expected win (6-0)",
                ntrpP1 = "3.5",
                ntrpP2 = "2.5",
                utrP1 = "7.5",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S8",
                description = "Low: 1.0 gap, upset (6-0)",
                ntrpP1 = "2.5",
                ntrpP2 = "3.5",
                utrP1 = "5.0",
                utrP2 = "7.5",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.642572",
                expectedNtrpP2Delta = "-0.642572",
                expectedUtrP1Delta = "1.606429",
                expectedUtrP2Delta = "-1.606429",
            ),
            RatingScenario(
                id = "S9",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "3.6",
                ntrpP2 = "3.5",
                utrP1 = "7.75",
                utrP2 = "7.5",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            RatingScenario(
                id = "S10",
                description = "Low: 1.5 gap, expected win (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "2.5",
                utrP1 = "8.75",
                utrP2 = "5.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S11",
                description = "Low: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "4.1",
                ntrpP2 = "4.0",
                utrP1 = "9.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            // NTRP 4.0-4.5 level (UTR 8.75-10.0 level)
            RatingScenario(
                id = "S12",
                description = "Mid: 2.0 gap, big upset (6-0)",
                ntrpP1 = "2.5",
                ntrpP2 = "4.5",
                utrP1 = "5.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "1.285139",
                expectedNtrpP2Delta = "-1.285139",
                expectedUtrP1Delta = "3.212848",
                expectedUtrP2Delta = "-3.212848",
            ),
            RatingScenario(
                id = "S13",
                description = "Mid: Expected win, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S14",
                description = "Mid: Expected win, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.0",
                utrP1 = "10.0",
                utrP2 = "8.75",
                p1Games = 6,
                p2Games = 4,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S15",
                description = "Mid: Upset, dominant (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "8.75",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.321284",
                expectedNtrpP2Delta = "-0.321284",
                expectedUtrP1Delta = "0.803210",
                expectedUtrP2Delta = "-0.803210",
            ),
            RatingScenario(
                id = "S16",
                description = "Mid: Upset, close (6-4)",
                ntrpP1 = "4.0",
                ntrpP2 = "4.5",
                utrP1 = "8.75",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "P1",
                expectedNtrpP1Delta = "0.064257",
                expectedNtrpP2Delta = "-0.064257",
                expectedUtrP1Delta = "0.160642",
                expectedUtrP2Delta = "-0.160642",
            ),
            RatingScenario(
                id = "S17",
                description = "Mid: Competitive, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.3",
                utrP1 = "10.0",
                utrP2 = "9.5",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.095744",
                expectedNtrpP2Delta = "-0.095744",
                expectedUtrP1Delta = "0.239359",
                expectedUtrP2Delta = "-0.239359",
            ),
            RatingScenario(
                id = "S18",
                description = "Mid: Competitive, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.3",
                utrP1 = "10.0",
                utrP2 = "9.5",
                p1Games = 6,
                p2Games = 4,
                winner = "P1",
                expectedNtrpP1Delta = "0.019149",
                expectedNtrpP2Delta = "-0.019149",
                expectedUtrP1Delta = "0.047872",
                expectedUtrP2Delta = "-0.047872",
            ),
            RatingScenario(
                id = "S19",
                description = "Mid: Equal players, dominant (6-0)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.5",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.160000",
                expectedNtrpP2Delta = "-0.160000",
                expectedUtrP1Delta = "0.400000",
                expectedUtrP2Delta = "-0.400000",
            ),
            RatingScenario(
                id = "S20",
                description = "Mid: Equal players, close (6-4)",
                ntrpP1 = "4.5",
                ntrpP2 = "4.5",
                utrP1 = "10.0",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 4,
                winner = "P1",
                expectedNtrpP1Delta = "0.032000",
                expectedNtrpP2Delta = "-0.032000",
                expectedUtrP1Delta = "0.080000",
                expectedUtrP2Delta = "-0.080000",
            ),
            RatingScenario(
                id = "S21",
                description = "Mid: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "4.6",
                ntrpP2 = "4.5",
                utrP1 = "10.25",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
            // NTRP 4.0-5.0 level (UTR 10.0-12.5 level) - Large gaps
            RatingScenario(
                id = "S22",
                description = "High: Large gap, expected win (6-0)",
                ntrpP1 = "5.0",
                ntrpP2 = "4.0",
                utrP1 = "12.5",
                utrP2 = "10.0",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.000000",
                expectedNtrpP2Delta = "0.000000",
                expectedUtrP1Delta = "0.000000",
                expectedUtrP2Delta = "0.000000",
            ),
            RatingScenario(
                id = "S23",
                description = "High: Large gap, big upset (6-0)",
                ntrpP1 = "4.0",
                ntrpP2 = "5.0",
                utrP1 = "10.0",
                utrP2 = "12.5",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.642572",
                expectedNtrpP2Delta = "-0.642572",
                expectedUtrP1Delta = "1.606429",
                expectedUtrP2Delta = "-1.606429",
            ),
            RatingScenario(
                id = "S24",
                description = "High: Below threshold, 0.1 gap (6-0)",
                ntrpP1 = "5.1",
                ntrpP2 = "5.0",
                utrP1 = "12.75",
                utrP2 = "12.5",
                p1Games = 6,
                p2Games = 0,
                winner = "P1",
                expectedNtrpP1Delta = "0.127871",
                expectedNtrpP2Delta = "-0.127871",
                expectedUtrP1Delta = "0.319677",
                expectedUtrP2Delta = "-0.319677",
            ),
        )
}
